# Generated by Django 4.1.13 on 2025-01-28 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exercises', models.TextField()),
                ('duration', models.DurationField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Dilluns', 'Dilluns'), ('Dimarts', 'Dimarts'), ('Dimecres', 'Dimecres'), ('Dijous', 'Dijous'), ('Divendres', 'Divendres')], max_length=10)),
                ('time', models.TimeField()),
                ('room', models.CharField(default='Sala Principal', max_length=255)),
                ('enrollments', models.ManyToManyField(blank=True, related_name='enrolled_schedules', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_trainer.routine')),
            ],
            options={
                'unique_together': {('day', 'time', 'room')},
            },
        ),
    ]
