# Generated by Django 4.1.13 on 2024-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1_routine', '1 rutina a la setmana - 15€ al mes'), ('3_routines', '3 rutines a la setmana - 30€ al mes'), ('unlimited', 'Rutines il·limitades - 50€ al mes')], max_length=50)),
                ('price', models.FloatField()),
                ('max_routines', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
